using System.Collections.Generic;

namespace Nop.Plugin.Payments.SafeTyPay.Models
{
    public class OperationActivityRequest
    {
        //String (Required, length = 32) Merchant API Key generated by using the MMS.
        public string ApiKey { get; set; } = null!;//23f1d7e1b2d44b7fb43e4bcddee45689

        //String (Required, ISO 8601: yyyy-MM-ddThh:mm:ss) Merchant Date and Time used to compose the signature
        public string RequestDateTime { get; set; } = null!;//2007-01-31T14:24:59

        //String (Required, max-length = 20) Reference number of the sale. This value is used to notify Merchants about a payment.
        public string MerchantSalesID { get; set; } = null!;//ORD-10001,

        //String Refer to https://developers.safetypay.com/docs/express-signature-calculator#section-getoperation
        public string Signature { get; set; } = null!;//HASH SHA256 of:
        // RequestDateTime +
        // SignatureKey

        //String(Optional) Format of response, DEFAULT CSV
        public string ResponseFormat { get; set; } = null!; //CSV, XML

        public List<KeyValuePair<string, string>> ToParameter()
        {
            return new List<KeyValuePair<string, string>>
            {
                new KeyValuePair<string, string>("ApiKey", ApiKey.Trim()),
                new KeyValuePair<string, string>("RequestDateTime", RequestDateTime),
                new KeyValuePair<string, string>("MerchantSalesID",MerchantSalesID),
                new KeyValuePair<string, string>("Signature", Signature),
                new KeyValuePair<string, string>("ResponseFormat", ResponseFormat)
            };
        }
    }
}